import { Lesson } from './types';

export const lessons: Lesson[] = [
  {
    id: 'basics',
    sectionId: 'js',
    order: 1,
    title: 'Переменные и базовый синтаксис',
    description:
      'Начинаем с объявления переменных, базовых операторов и первых выражений.',
    path: '/js/lessons/basics',
    rows: [
      {
        title: 'let',
        description: 'Создает изменяемую переменную в блочной области видимости.',
        example: 'let age = 18;\nage = 19;',
        result: 'В переменной age будет 19',
      },
      {
        title: 'const',
        description: 'Создает константу, ссылку которой нельзя переназначить.',
        example: 'const course = "JavaScript";',
        result: 'course === "JavaScript"',
      },
      {
        title: 'typeof',
        description: 'Возвращает строку с типом значения.',
        example: 'typeof 42',
        result: '"number"',
      },
      {
        title: '= и ===',
        description:
          'Оператор = присваивает значение, а === строго сравнивает без приведения типов.',
        example: '5 === "5"',
        result: 'false',
      },
      {
        title: 'Шаблонная строка',
        description: 'Позволяет вставлять выражения через ${...}.',
        example: 'const name = "Анна";\n`Привет, ${name}!`',
        result: '"Привет, Анна!"',
      },
    ],
  },
  {
    id: 'data-types',
    sectionId: 'js',
    order: 2,
    title: 'Типы данных',
    description:
      'После переменных логично изучить основные примитивы и объекты JavaScript.',
    path: '/js/lessons/data-types',
    rows: [
      {
        title: 'Number',
        description: 'Числовой тип для целых и дробных значений.',
        example: 'const price = 199.99;',
        result: 'price хранит число 199.99',
      },
      {
        title: 'String',
        description: 'Тип для текстовых значений.',
        example: 'const language = "JS";',
        result: 'language хранит строку "JS"',
      },
      {
        title: 'Boolean',
        description: 'Логический тип: true или false.',
        example: 'Boolean(1)',
        result: 'true',
      },
      {
        title: 'Null',
        description: 'Специальное значение для намеренного отсутствия данных.',
        example: 'const selectedUser = null;',
        result: 'selectedUser содержит null',
      },
      {
        title: 'Undefined',
        description: 'Значение переменной, которой ничего не присвоили.',
        example: 'let city;\nconsole.log(city);',
        result: 'undefined',
      },
      {
        title: 'Symbol',
        description: 'Создает уникальный идентификатор.',
        example: 'const id = Symbol("id");',
        result: 'Каждый Symbol уникален',
      },
      {
        title: 'BigInt',
        description: 'Используется для очень больших целых чисел.',
        example: 'const value = 9007199254740993n;',
        result: 'value хранит BigInt',
      },
      {
        title: 'Object',
        description: 'Структура для хранения связанных значений по ключам.',
        example: 'const user = { name: "Игорь", level: "junior" };',
        result: 'user.name === "Игорь"',
      },
    ],
  },
  {
    id: 'type-conversion',
    sectionId: 'js',
    order: 3,
    title: 'Преобразование типов',
    description:
      'Следующий шаг после типов данных: понять, как JavaScript приводит значения.',
    path: '/js/lessons/type-conversion',
    rows: [
      {
        title: 'Number()',
        description: 'Преобразует значение в число.',
        example: 'Number("42")',
        result: '42',
      },
      {
        title: 'String()',
        description: 'Преобразует значение в строку.',
        example: 'String(2026)',
        result: '"2026"',
      },
      {
        title: 'Boolean()',
        description: 'Преобразует значение в true или false.',
        example: 'Boolean("")',
        result: 'false',
      },
      {
        title: 'Неявное приведение',
        description: 'Некоторые операторы автоматически меняют типы значений.',
        example: '"5" + 2',
        result: '"52"',
      },
      {
        title: 'parseInt()',
        description: 'Извлекает целое число из строки.',
        example: 'parseInt("15px", 10)',
        result: '15',
      },
      {
        title: 'parseFloat()',
        description: 'Извлекает число с плавающей точкой из строки.',
        example: 'parseFloat("3.14rem")',
        result: '3.14',
      },
    ],
  },
  {
    id: 'operators',
    sectionId: 'js',
    order: 4,
    title: 'Операторы',
    description:
      'Теперь можно пройти арифметические, логические и специальные операторы языка.',
    path: '/js/lessons/operators',
    rows: [
      {
        title: '+, -, *, /, %',
        description: 'Базовые арифметические операторы.',
        example: '10 % 3',
        result: '1',
      },
      {
        title: '++ и --',
        description: 'Увеличивают или уменьшают значение на единицу.',
        example: 'let n = 1;\nn += 1;',
        result: 'n станет 2',
      },
      {
        title: '??',
        description: 'Возвращает правое значение, если левое равно null или undefined.',
        example: 'null ?? "default"',
        result: '"default"',
      },
      {
        title: '?.',
        description: 'Безопасно обращается к свойству, если объект существует.',
        example: 'user?.profile?.name',
        result: 'undefined, если profile отсутствует',
      },
      {
        title: '... spread',
        description: 'Разворачивает элементы массива или свойства объекта.',
        example: 'const copy = [...[1, 2, 3]];',
        result: 'copy === [1, 2, 3]',
      },
      {
        title: '... rest',
        description: 'Собирает оставшиеся аргументы или свойства.',
        example: 'const [first, ...rest] = [1, 2, 3];',
        result: 'rest === [2, 3]',
      },
    ],
  },
  {
    id: 'strings',
    sectionId: 'js',
    order: 5,
    title: 'Работа со строками',
    description:
      'Дальше переходим к строкам: поиск, преобразование, разбиение и объединение.',
    path: '/js/lessons/strings',
    rows: [
      {
        title: 'length',
        description: 'Возвращает количество символов в строке.',
        example: '"frontend".length',
        result: '8',
      },
      {
        title: 'toUpperCase()',
        description: 'Преобразует строку в верхний регистр.',
        example: '"js".toUpperCase()',
        result: '"JS"',
      },
      {
        title: 'includes()',
        description: 'Проверяет, содержит ли строка подстроку.',
        example: '"javascript".includes("script")',
        result: 'true',
      },
      {
        title: 'slice()',
        description: 'Извлекает часть строки по индексам.',
        example: '"JavaScript".slice(0, 4)',
        result: '"Java"',
      },
      {
        title: 'replace()',
        description: 'Заменяет часть строки на новое значение.',
        example: '"Hello JS".replace("JS", "TS")',
        result: '"Hello TS"',
      },
      {
        title: 'split()',
        description: 'Разбивает строку на массив по разделителю.',
        example: '"HTML,CSS,JS".split(",")',
        result: '["HTML", "CSS", "JS"]',
      },
      {
        title: 'trim()',
        description: 'Удаляет пробелы в начале и конце строки.',
        example: '"  hello  ".trim()',
        result: '"hello"',
      },
    ],
  },
  {
    id: 'math',
    sectionId: 'js',
    order: 6,
    title: 'Математические функции',
    description:
      'После строк удобно изучить встроенный объект Math и числовые операции.',
    path: '/js/lessons/math',
    rows: [
      {
        title: 'Math.floor()',
        description: 'Округляет число вниз до ближайшего целого.',
        example: 'Math.floor(4.9)',
        result: '4',
      },
      {
        title: 'Math.ceil()',
        description: 'Округляет число вверх до ближайшего целого.',
        example: 'Math.ceil(4.1)',
        result: '5',
      },
      {
        title: 'Math.round()',
        description: 'Округляет по правилам математики.',
        example: 'Math.round(4.5)',
        result: '5',
      },
      {
        title: 'Math.max()',
        description: 'Возвращает наибольшее число из набора.',
        example: 'Math.max(3, 7, 2)',
        result: '7',
      },
      {
        title: 'Math.min()',
        description: 'Возвращает наименьшее число из набора.',
        example: 'Math.min(3, 7, 2)',
        result: '2',
      },
      {
        title: 'Math.random()',
        description: 'Возвращает случайное число от 0 до 1, не включая 1.',
        example: 'Math.random()',
        result: 'Например, 0.347281...',
      },
      {
        title: 'toFixed()',
        description: 'Форматирует число с указанным количеством знаков после запятой.',
        example: '(3.14159).toFixed(2)',
        result: '"3.14"',
      },
    ],
  },
  {
    id: 'conditions',
    sectionId: 'js',
    order: 7,
    title: 'Условия и сравнения',
    description:
      'Прежде чем переходить к циклам, важно освоить ветвление и логические операторы.',
    path: '/js/lessons/conditions',
    rows: [
      {
        title: 'if',
        description: 'Выполняет блок кода, если условие истинно.',
        example: 'if (score >= 60) {\n  "Зачет";\n}',
        result: 'Блок выполнится только при score >= 60',
      },
      {
        title: 'if...else',
        description: 'Позволяет задать альтернативный сценарий.',
        example: 'const result = age >= 18 ? "adult" : "minor";',
        result: 'result зависит от условия',
      },
      {
        title: '=== и !==',
        description: 'Строго сравнивают значения без приведения типов.',
        example: '10 !== "10"',
        result: 'true',
      },
      {
        title: '&&',
        description: 'Возвращает true, если оба условия истинны.',
        example: 'true && false',
        result: 'false',
      },
      {
        title: '||',
        description: 'Возвращает true, если хотя бы одно условие истинно.',
        example: 'false || true',
        result: 'true',
      },
      {
        title: 'switch',
        description: 'Удобен для выбора одного из нескольких сценариев.',
        example:
          'switch (role) {\n  case "admin": return "full";\n  default: return "limited";\n}',
        result: 'Вернется значение для подходящего case',
      },
    ],
  },
  {
    id: 'loops',
    sectionId: 'js',
    order: 8,
    title: 'Циклы',
    description:
      'Завершаем блок базового синтаксиса циклами, чтобы повторять действия и обходить коллекции.',
    path: '/js/lessons/loops',
    rows: [
      {
        title: 'for',
        description: 'Классический цикл с инициализацией, условием и шагом.',
        example: 'for (let i = 0; i < 3; i += 1) {\n  console.log(i);\n}',
        result: 'В консоль выведется 0, 1, 2',
      },
      {
        title: 'while',
        description: 'Повторяет код, пока условие истинно.',
        example: 'let n = 0;\nwhile (n < 2) {\n  n += 1;\n}',
        result: 'После цикла n будет равно 2',
      },
      {
        title: 'do...while',
        description: 'Гарантирует хотя бы одно выполнение блока.',
        example: 'let count = 3;\ndo {\n  count += 1;\n} while (count < 3);',
        result: 'count станет 4',
      },
      {
        title: 'for...of',
        description: 'Перебирает значения итерируемого объекта.',
        example: 'for (const item of ["a", "b"]) {\n  console.log(item);\n}',
        result: 'В консоль выведется "a", затем "b"',
      },
      {
        title: 'for...in',
        description: 'Перебирает ключи объекта.',
        example: 'for (const key in { a: 1, b: 2 }) {\n  console.log(key);\n}',
        result: 'В консоль выведется "a" и "b"',
      },
      {
        title: 'break',
        description: 'Прерывает выполнение цикла.',
        example: 'for (let i = 0; i < 5; i += 1) {\n  if (i === 2) break;\n}',
        result: 'Цикл остановится при i === 2',
      },
      {
        title: 'continue',
        description: 'Пропускает текущую итерацию и переходит к следующей.',
        example:
          'for (let i = 0; i < 3; i += 1) {\n  if (i === 1) continue;\n  console.log(i);\n}',
        result: 'В консоль выведется 0 и 2',
      },
    ],
  },
  {
    id: 'functions',
    sectionId: 'js',
    order: 9,
    title: 'Функции',
    description:
      'После синтаксических основ переходим к функциям как к основному способу организации кода.',
    path: '/js/lessons/functions',
    rows: [
      {
        title: 'function declaration',
        description: 'Объявляет функцию, доступную до места вызова.',
        example: 'function sum(a, b) {\n  return a + b;\n}',
        result: 'sum(2, 3) вернет 5',
      },
      {
        title: 'function expression',
        description: 'Функция сохраняется в переменной.',
        example: 'const multiply = function (a, b) {\n  return a * b;\n};',
        result: 'multiply(2, 4) вернет 8',
      },
      {
        title: 'arrow function',
        description: 'Короткая форма записи функции.',
        example: 'const square = (n) => n * n;',
        result: 'square(3) вернет 9',
      },
      {
        title: 'return',
        description: 'Возвращает значение из функции.',
        example: 'function getName() {\n  return "JS";\n}',
        result: 'Вызов getName() вернет "JS"',
      },
      {
        title: 'Параметры по умолчанию',
        description: 'Задают значение, если аргумент не передан.',
        example: 'const greet = (name = "Гость") => `Привет, ${name}`;',
        result: 'greet() вернет "Привет, Гость"',
      },
      {
        title: 'arguments / rest',
        description: 'Rest-параметр собирает все оставшиеся аргументы.',
        example: 'const sumAll = (...nums) => nums.length;',
        result: 'sumAll(1, 2, 3) вернет 3',
      },
    ],
  },
  {
    id: 'arrays-basics',
    sectionId: 'js',
    order: 10,
    title: 'Массивы',
    description:
      'Следующий естественный этап: хранение списков данных и базовые операции с массивами.',
    path: '/js/lessons/arrays-basics',
    rows: [
      {
        title: 'length',
        description: 'Показывает количество элементов массива.',
        example: '[10, 20, 30].length',
        result: '3',
      },
      {
        title: 'push()',
        description: 'Добавляет элемент в конец массива.',
        example: 'const arr = [1, 2];\narr.push(3);',
        result: 'arr === [1, 2, 3]',
      },
      {
        title: 'pop()',
        description: 'Удаляет последний элемент и возвращает его.',
        example: 'const arr = [1, 2, 3];\narr.pop();',
        result: 'Вернется 3, массив станет [1, 2]',
      },
      {
        title: 'shift()',
        description: 'Удаляет первый элемент массива.',
        example: 'const arr = ["a", "b"];\narr.shift();',
        result: 'Вернется "a", массив станет ["b"]',
      },
      {
        title: 'unshift()',
        description: 'Добавляет элемент в начало массива.',
        example: 'const arr = [2, 3];\narr.unshift(1);',
        result: 'arr === [1, 2, 3]',
      },
      {
        title: 'at()',
        description: 'Возвращает элемент по индексу, поддерживает отрицательные значения.',
        example: '["x", "y", "z"].at(-1)',
        result: '"z"',
      },
    ],
  },
  {
    id: 'array-methods',
    sectionId: 'js',
    order: 11,
    title: 'Методы массивов',
    description:
      'После базовых операций изучаем основные методы обработки массивов.',
    path: '/js/lessons/array-methods',
    rows: [
      {
        title: 'forEach()',
        description: 'Вызывает функцию для каждого элемента массива.',
        example: '[1, 2].forEach((n) => console.log(n));',
        result: 'В консоль выведется 1 и 2',
      },
      {
        title: 'map()',
        description: 'Создает новый массив на основе результата функции.',
        example: '[1, 2, 3].map((n) => n * 2)',
        result: '[2, 4, 6]',
      },
      {
        title: 'filter()',
        description: 'Оставляет элементы, для которых условие истинно.',
        example: '[1, 2, 3, 4].filter((n) => n % 2 === 0)',
        result: '[2, 4]',
      },
      {
        title: 'find()',
        description: 'Возвращает первый найденный элемент.',
        example: '[5, 8, 12].find((n) => n > 6)',
        result: '8',
      },
      {
        title: 'some()',
        description: 'Проверяет, есть ли хотя бы один подходящий элемент.',
        example: '[1, 3, 5].some((n) => n % 2 === 0)',
        result: 'false',
      },
      {
        title: 'every()',
        description: 'Проверяет, удовлетворяют ли условию все элементы.',
        example: '[2, 4, 6].every((n) => n % 2 === 0)',
        result: 'true',
      },
      {
        title: 'reduce()',
        description: 'Сворачивает массив в одно итоговое значение.',
        example: '[1, 2, 3].reduce((acc, n) => acc + n, 0)',
        result: '6',
      },
    ],
  },
  {
    id: 'objects',
    sectionId: 'js',
    order: 12,
    title: 'Объекты',
    description:
      'Далее переходим к объектам: свойствам, ключам и работе со структурированными данными.',
    path: '/js/lessons/objects',
    rows: [
      {
        title: 'Свойства объекта',
        description: 'Доступ к свойству можно получить через точку или квадратные скобки.',
        example: 'const user = { name: "Лена" };\nuser.name;',
        result: '"Лена"',
      },
      {
        title: 'Object.keys()',
        description: 'Возвращает массив ключей объекта.',
        example: 'Object.keys({ a: 1, b: 2 })',
        result: '["a", "b"]',
      },
      {
        title: 'Object.values()',
        description: 'Возвращает массив значений объекта.',
        example: 'Object.values({ a: 1, b: 2 })',
        result: '[1, 2]',
      },
      {
        title: 'Object.entries()',
        description: 'Возвращает пары [ключ, значение].',
        example: 'Object.entries({ a: 1 })',
        result: '[["a", 1]]',
      },
      {
        title: 'in',
        description: 'Проверяет наличие свойства в объекте.',
        example: '"name" in { name: "Ира" }',
        result: 'true',
      },
      {
        title: 'delete',
        description: 'Удаляет свойство из объекта.',
        example: 'const obj = { x: 1 };\ndelete obj.x;',
        result: 'obj станет {}',
      },
    ],
  },
  {
    id: 'destructuring',
    sectionId: 'js',
    order: 13,
    title: 'Деструктуризация',
    description:
      'Удобный синтаксис для извлечения значений из массивов и объектов.',
    path: '/js/lessons/destructuring',
    rows: [
      {
        title: 'Деструктуризация массива',
        description: 'Позволяет достать элементы массива в переменные.',
        example: 'const [first, second] = ["JS", "TS"];',
        result: 'first === "JS", second === "TS"',
      },
      {
        title: 'Деструктуризация объекта',
        description: 'Позволяет быстро получить свойства объекта.',
        example: 'const { name, age } = { name: "Оля", age: 22 };',
        result: 'name === "Оля", age === 22',
      },
      {
        title: 'Переименование',
        description: 'Свойство можно сохранить под другим именем.',
        example: 'const { name: userName } = { name: "Max" };',
        result: 'userName === "Max"',
      },
      {
        title: 'Значения по умолчанию',
        description: 'Можно указать запасное значение для отсутствующего свойства.',
        example: 'const { role = "student" } = {};',
        result: 'role === "student"',
      },
      {
        title: 'Rest в деструктуризации',
        description: 'Собирает оставшиеся элементы или свойства.',
        example: 'const { a, ...rest } = { a: 1, b: 2, c: 3 };',
        result: 'rest === { b: 2, c: 3 }',
      },
    ],
  },
  {
    id: 'this-context',
    sectionId: 'js',
    order: 14,
    title: 'Контекст this',
    description:
      'После объектов важно понять, как работает this в разных сценариях вызова.',
    path: '/js/lessons/this-context',
    rows: [
      {
        title: 'this в методе объекта',
        description: 'В обычном методе this ссылается на объект вызова.',
        example: 'const user = { name: "Илья", getName() { return this.name; } };',
        result: 'user.getName() вернет "Илья"',
      },
      {
        title: 'this в стрелочной функции',
        description: 'Стрелочная функция не имеет собственного this.',
        example: 'const obj = { value: 1, get: () => this.value };',
        result: 'this берется из внешнего окружения',
      },
      {
        title: 'bind()',
        description: 'Создает новую функцию с фиксированным this.',
        example: 'const bound = fn.bind(user);',
        result: 'При вызове bound this будет user',
      },
      {
        title: 'call()',
        description: 'Вызывает функцию с указанным this и аргументами.',
        example: 'fn.call(user, 1, 2);',
        result: 'Функция выполнится сразу',
      },
      {
        title: 'apply()',
        description: 'Похожа на call, но аргументы передаются массивом.',
        example: 'fn.apply(user, [1, 2]);',
        result: 'Функция выполнится с this = user',
      },
    ],
  },
  {
    id: 'classes',
    sectionId: 'js',
    order: 15,
    title: 'Классы и наследование',
    description:
      'Дальше можно изучить синтаксис классов и базовые принципы ООП в JavaScript.',
    path: '/js/lessons/classes',
    rows: [
      {
        title: 'class',
        description: 'Определяет шаблон для создания объектов.',
        example: 'class User {\n  constructor(name) {\n    this.name = name;\n  }\n}',
        result: 'new User("Ann") создаст экземпляр',
      },
      {
        title: 'constructor',
        description: 'Инициализирует объект при создании.',
        example: 'constructor(title) {\n  this.title = title;\n}',
        result: 'Свойство title будет сохранено в экземпляре',
      },
      {
        title: 'method',
        description: 'Метод класса доступен всем экземплярам через prototype.',
        example: 'sayHi() {\n  return `Hi, ${this.name}`;\n}',
        result: 'Экземпляр сможет вызвать sayHi()',
      },
      {
        title: 'extends',
        description: 'Позволяет одному классу наследоваться от другого.',
        example: 'class Admin extends User {}',
        result: 'Admin получит поведение User',
      },
      {
        title: 'super()',
        description: 'Вызывает конструктор родительского класса.',
        example: 'constructor(name, role) {\n  super(name);\n  this.role = role;\n}',
        result: 'Сначала инициализируется базовый класс',
      },
    ],
  },
  {
    id: 'date-timers',
    sectionId: 'js',
    order: 16,
    title: 'Дата и таймеры',
    description:
      'Практически полезный блок: работа со временем и отложенным выполнением.',
    path: '/js/lessons/date-timers',
    rows: [
      {
        title: 'Date',
        description: 'Создает объект даты и времени.',
        example: 'const now = new Date();',
        result: 'now хранит текущую дату и время',
      },
      {
        title: 'getFullYear()',
        description: 'Возвращает год из объекта Date.',
        example: 'new Date("2026-03-28").getFullYear()',
        result: '2026',
      },
      {
        title: 'toLocaleDateString()',
        description: 'Форматирует дату в локальный вид.',
        example: 'new Date("2026-03-28").toLocaleDateString("ru-RU")',
        result: 'Например, "28.03.2026"',
      },
      {
        title: 'setTimeout()',
        description: 'Выполняет функцию один раз с задержкой.',
        example: 'setTimeout(() => console.log("ready"), 1000);',
        result: 'Через 1 секунду выведется "ready"',
      },
      {
        title: 'setInterval()',
        description: 'Повторяет выполнение функции через равные интервалы.',
        example: 'const id = setInterval(() => console.log("tick"), 1000);',
        result: 'Каждую секунду будет выводиться "tick"',
      },
      {
        title: 'clearTimeout / clearInterval',
        description: 'Останавливают ранее запланированный таймер.',
        example: 'clearInterval(id);',
        result: 'Повторения прекратятся',
      },
    ],
  },
  {
    id: 'json-storage',
    sectionId: 'js',
    order: 17,
    title: 'JSON и хранение данных',
    description:
      'После работы с объектами и строками полезно изучить сериализацию и локальное хранилище.',
    path: '/js/lessons/json-storage',
    rows: [
      {
        title: 'JSON.stringify()',
        description: 'Преобразует объект в JSON-строку.',
        example: 'JSON.stringify({ name: "JS" })',
        result: '"{\\"name\\":\\"JS\\"}"',
      },
      {
        title: 'JSON.parse()',
        description: 'Преобразует JSON-строку обратно в объект.',
        example: 'JSON.parse("{\\"name\\":\\"JS\\"}")',
        result: '{ name: "JS" }',
      },
      {
        title: 'localStorage.setItem()',
        description: 'Сохраняет строковое значение в браузере.',
        example: 'localStorage.setItem("theme", "dark");',
        result: 'В storage сохранится ключ theme',
      },
      {
        title: 'localStorage.getItem()',
        description: 'Читает значение по ключу.',
        example: 'localStorage.getItem("theme")',
        result: '"dark" или null',
      },
      {
        title: 'sessionStorage',
        description: 'Хранит данные до закрытия вкладки браузера.',
        example: 'sessionStorage.setItem("token", "123");',
        result: 'Данные сохранятся в рамках текущей сессии',
      },
    ],
  },
  {
    id: 'errors',
    sectionId: 'js',
    order: 18,
    title: 'Ошибки и отладка',
    description:
      'Теперь важно понять, как обрабатывать ошибки и искать проблемы в коде.',
    path: '/js/lessons/errors',
    rows: [
      {
        title: 'try...catch',
        description: 'Позволяет перехватить ошибку и продолжить выполнение.',
        example: 'try {\n  JSON.parse("bad");\n} catch (error) {\n  console.log(error.message);\n}',
        result: 'Ошибка будет обработана в catch',
      },
      {
        title: 'finally',
        description: 'Выполняется независимо от того, была ошибка или нет.',
        example: 'try {\n  run();\n} finally {\n  cleanup();\n}',
        result: 'cleanup() выполнится в любом случае',
      },
      {
        title: 'throw',
        description: 'Позволяет выбросить собственную ошибку.',
        example: 'throw new Error("Неверные данные");',
        result: 'Выполнение прервется с ошибкой',
      },
      {
        title: 'console.log()',
        description: 'Выводит данные в консоль для проверки состояния программы.',
        example: 'console.log(user);',
        result: 'Объект user появится в консоли',
      },
      {
        title: 'console.table()',
        description: 'Показывает массивы объектов в табличном виде.',
        example: 'console.table([{ id: 1 }, { id: 2 }]);',
        result: 'В консоли появится таблица',
      },
    ],
  },
  {
    id: 'async-basics',
    sectionId: 'js',
    order: 19,
    title: 'Асинхронность',
    description:
      'После синхронного кода переходим к промисам и современному асинхронному синтаксису.',
    path: '/js/lessons/async-basics',
    rows: [
      {
        title: 'Promise',
        description: 'Объект, представляющий результат асинхронной операции.',
        example: 'const promise = new Promise((resolve) => resolve("done"));',
        result: 'promise перейдет в состояние fulfilled',
      },
      {
        title: '.then()',
        description: 'Обрабатывает успешное завершение Promise.',
        example: 'promise.then((value) => console.log(value));',
        result: 'В консоль выведется "done"',
      },
      {
        title: '.catch()',
        description: 'Обрабатывает ошибку Promise.',
        example: 'promise.catch((error) => console.error(error));',
        result: 'Ошибки будут перехвачены',
      },
      {
        title: 'async',
        description: 'Помечает функцию как асинхронную и возвращающую Promise.',
        example: 'async function load() {\n  return 5;\n}',
        result: 'load() вернет Promise со значением 5',
      },
      {
        title: 'await',
        description: 'Ожидает завершения Promise внутри async-функции.',
        example: 'const data = await Promise.resolve("ok");',
        result: 'data будет равно "ok"',
      },
      {
        title: 'Promise.all()',
        description: 'Ожидает завершения всех Promise в массиве.',
        example: 'await Promise.all([Promise.resolve(1), Promise.resolve(2)]);',
        result: '[1, 2]',
      },
    ],
  },
  {
    id: 'fetch-api',
    sectionId: 'js',
    order: 20,
    title: 'Сетевые запросы',
    description:
      'Следом за асинхронностью изучаем получение данных с сервера через Fetch API.',
    path: '/js/lessons/fetch-api',
    rows: [
      {
        title: 'fetch()',
        description: 'Отправляет HTTP-запрос и возвращает Promise с Response.',
        example: 'const response = await fetch("/api/posts");',
        result: 'response будет объектом Response',
      },
      {
        title: 'response.json()',
        description: 'Читает тело ответа как JSON.',
        example: 'const data = await response.json();',
        result: 'data будет JS-объектом',
      },
      {
        title: 'method',
        description: 'Позволяет указать HTTP-метод запроса.',
        example: 'fetch("/api/posts", { method: "POST" });',
        result: 'Будет выполнен POST-запрос',
      },
      {
        title: 'headers',
        description: 'Используются для передачи метаданных запроса.',
        example: 'fetch(url, { headers: { "Content-Type": "application/json" } });',
        result: 'Сервер получит заголовок Content-Type',
      },
      {
        title: 'body',
        description: 'Передает тело запроса для POST, PUT и PATCH.',
        example: 'fetch(url, { body: JSON.stringify({ title: "JS" }) });',
        result: 'На сервер уйдет JSON-строка',
      },
    ],
  },
  {
    id: 'dom-basics',
    sectionId: 'js',
    order: 21,
    title: 'DOM и события',
    description:
      'Дальше идет браузерная часть JavaScript: поиск элементов, изменение DOM и обработка событий.',
    path: '/js/lessons/dom-basics',
    rows: [
      {
        title: 'document.querySelector()',
        description: 'Находит первый элемент по CSS-селектору.',
        example: 'document.querySelector(".card")',
        result: 'Вернет найденный элемент или null',
      },
      {
        title: 'textContent',
        description: 'Читает или изменяет текстовое содержимое элемента.',
        example: 'title.textContent = "Новый заголовок";',
        result: 'Текст элемента изменится',
      },
      {
        title: 'classList.add()',
        description: 'Добавляет CSS-класс элементу.',
        example: 'button.classList.add("active");',
        result: 'У элемента появится класс active',
      },
      {
        title: 'addEventListener()',
        description: 'Подписывает элемент на событие.',
        example: 'button.addEventListener("click", handleClick);',
        result: 'При клике вызовется handleClick',
      },
      {
        title: 'event.preventDefault()',
        description: 'Отменяет действие браузера по умолчанию.',
        example: 'form.addEventListener("submit", (event) => event.preventDefault());',
        result: 'Форма не будет отправлена стандартным способом',
      },
      {
        title: 'createElement()',
        description: 'Создает новый DOM-элемент программно.',
        example: 'const item = document.createElement("li");',
        result: 'item будет новым элементом <li>',
      },
    ],
  },
  {
    id: 'modules',
    sectionId: 'js',
    order: 22,
    title: 'Модули',
    description:
      'Финальный базовый раздел: разбиение кода по файлам и повторное использование логики.',
    path: '/js/lessons/modules',
    rows: [
      {
        title: 'export',
        description: 'Экспортирует переменную, функцию или класс из файла.',
        example: 'export const apiUrl = "/api";',
        result: 'apiUrl можно импортировать в другом модуле',
      },
      {
        title: 'export default',
        description: 'Экспортирует одно основное значение из файла.',
        example: 'export default function App() {}',
        result: 'Модуль получит default-экспорт',
      },
      {
        title: 'import',
        description: 'Подключает именованный или default-экспорт из другого файла.',
        example: 'import App from "./App";',
        result: 'В текущем файле станет доступен App',
      },
      {
        title: 'import { ... }',
        description: 'Подключает именованные экспорты.',
        example: 'import { apiUrl } from "./config";',
        result: 'В текущем файле станет доступен apiUrl',
      },
      {
        title: 're-export',
        description: 'Позволяет переэкспортировать сущности через index-файл.',
        example: 'export { Button } from "./Button";',
        result: 'Импорт можно делать через общий входной файл',
      },
    ],
  },
  {
    id: 'html-basics',
    sectionId: 'html',
    order: 1,
    title: 'Базовая структура HTML',
    description: 'Начинаем с каркаса документа, метаданных и базовых тегов страницы.',
    path: '/html/lessons/html-basics',
    rows: [
      {
        title: '<!DOCTYPE html>',
        description: 'Сообщает браузеру, что используется современный HTML5.',
        example: '<!DOCTYPE html>',
        result: 'Браузер рендерит страницу в стандартном режиме',
      },
      {
        title: '<html>',
        description: 'Корневой элемент HTML-документа.',
        example: '<html lang="ru">...</html>',
        result: 'Внутри элемента находится весь документ',
      },
      {
        title: '<head>',
        description: 'Содержит метаданные, заголовок и подключения ресурсов.',
        example: '<head><title>Page</title></head>',
        result: 'Метаданные не отображаются как контент страницы',
      },
      {
        title: '<body>',
        description: 'Содержит видимую часть страницы.',
        example: '<body><h1>Hello</h1></body>',
        result: 'Пользователь увидит заголовок Hello',
      },
      {
        title: '<meta charset="UTF-8">',
        description: 'Задает кодировку документа.',
        example: '<meta charset="UTF-8" />',
        result: 'Русский текст отображается корректно',
      },
    ],
  },
  {
    id: 'html-text',
    sectionId: 'html',
    order: 2,
    title: 'Текст и семантика',
    description: 'После каркаса изучаем заголовки, абзацы и смысловые теги.',
    path: '/html/lessons/html-text',
    rows: [
      {
        title: '<h1>...<h6>',
        description: 'Заголовки разного уровня важности.',
        example: '<h1>Главная тема</h1>',
        result: 'На странице появится крупный заголовок',
      },
      {
        title: '<p>',
        description: 'Создает абзац текста.',
        example: '<p>Это учебный абзац.</p>',
        result: 'Текст будет оформлен как отдельный блок',
      },
      {
        title: '<strong>',
        description: 'Подчеркивает важность части текста.',
        example: '<strong>Важно</strong>',
        result: 'Текст обычно отображается жирным',
      },
      {
        title: '<em>',
        description: 'Выделяет смысловой акцент в тексте.',
        example: '<em>Подчеркнутый смысл</em>',
        result: 'Текст обычно отображается курсивом',
      },
      {
        title: '<article>, <section>, <main>',
        description: 'Семантические контейнеры для структуры страницы.',
        example: '<main><section><article>Контент</article></section></main>',
        result: 'Разметка становится понятнее для браузера и ассистивных технологий',
      },
    ],
  },
  {
    id: 'html-links-media',
    sectionId: 'html',
    order: 3,
    title: 'Ссылки, изображения и медиа',
    description: 'Дальше нужны основные элементы навигации и визуального контента.',
    path: '/html/lessons/html-links-media',
    rows: [
      {
        title: '<a>',
        description: 'Создает ссылку на страницу, файл или секцию.',
        example: '<a href="/about">О нас</a>',
        result: 'Пользователь сможет перейти по ссылке',
      },
      {
        title: 'target="_blank"',
        description: 'Открывает ссылку в новой вкладке.',
        example: '<a href="https://example.com" target="_blank">Open</a>',
        result: 'Ссылка откроется в новой вкладке',
      },
      {
        title: '<img>',
        description: 'Вставляет изображение на страницу.',
        example: '<img src="photo.jpg" alt="Описание" />',
        result: 'На странице появится изображение',
      },
      {
        title: '<video>',
        description: 'Встраивает видеоконтент.',
        example: '<video controls src="movie.mp4"></video>',
        result: 'Появится видеоплеер',
      },
      {
        title: '<audio>',
        description: 'Встраивает аудиоконтент.',
        example: '<audio controls src="sound.mp3"></audio>',
        result: 'Появится аудиоплеер',
      },
    ],
  },
  {
    id: 'html-lists-tables',
    sectionId: 'html',
    order: 4,
    title: 'Списки и таблицы',
    description: 'Следующий блок для структурирования повторяющихся данных.',
    path: '/html/lessons/html-lists-tables',
    rows: [
      {
        title: '<ul>',
        description: 'Создает маркированный список.',
        example: '<ul><li>HTML</li><li>CSS</li></ul>',
        result: 'Появится список с маркерами',
      },
      {
        title: '<ol>',
        description: 'Создает нумерованный список.',
        example: '<ol><li>Шаг 1</li><li>Шаг 2</li></ol>',
        result: 'Список будет пронумерован',
      },
      {
        title: '<table>',
        description: 'Создает таблицу для данных в строках и столбцах.',
        example: '<table><tr><td>1</td></tr></table>',
        result: 'На странице появится таблица',
      },
      {
        title: '<thead>, <tbody>',
        description: 'Разделяют заголовок и основную часть таблицы.',
        example: '<thead><tr><th>Имя</th></tr></thead>',
        result: 'Таблица получает логичную структуру',
      },
      {
        title: '<th>',
        description: 'Ячейка заголовка таблицы.',
        example: '<th>Возраст</th>',
        result: 'Текст ячейки будет восприниматься как заголовок столбца',
      },
    ],
  },
  {
    id: 'html-forms',
    sectionId: 'html',
    order: 5,
    title: 'Формы',
    description: 'Завершаем базовый HTML формами и элементами ввода.',
    path: '/html/lessons/html-forms',
    rows: [
      {
        title: '<form>',
        description: 'Контейнер для полей ввода и отправки данных.',
        example: '<form action="/submit"></form>',
        result: 'Форма сможет отправлять данные',
      },
      {
        title: '<input>',
        description: 'Базовое поле ввода разных типов.',
        example: '<input type="email" />',
        result: 'Появится поле для email',
      },
      {
        title: '<label>',
        description: 'Связывает подпись с полем формы.',
        example: '<label for="name">Имя</label>',
        result: 'Подпись улучшает доступность формы',
      },
      {
        title: '<textarea>',
        description: 'Многострочное поле ввода.',
        example: '<textarea></textarea>',
        result: 'Появится поле для длинного текста',
      },
      {
        title: '<button>',
        description: 'Кнопка действия внутри формы или вне ее.',
        example: '<button type="submit">Отправить</button>',
        result: 'Кнопка отправит форму',
      },
    ],
  },
  {
    id: 'css-basics',
    sectionId: 'css',
    order: 1,
    title: 'Основы CSS',
    description: 'Стартуем с подключения стилей, селекторов и базовых свойств.',
    path: '/css/lessons/css-basics',
    rows: [
      {
        title: 'color',
        description: 'Задает цвет текста.',
        example: 'color: #ffffff;',
        result: 'Текст элемента станет белым',
      },
      {
        title: 'background',
        description: 'Устанавливает фон элемента.',
        example: 'background: #1e293b;',
        result: 'Фон элемента станет темно-синим',
      },
      {
        title: 'font-size',
        description: 'Задает размер шрифта.',
        example: 'font-size: 18px;',
        result: 'Размер текста станет 18px',
      },
      {
        title: 'class selector',
        description: 'Применяет стили ко всем элементам с указанным классом.',
        example: '.card { padding: 20px; }',
        result: 'Элементы с классом card получат внутренний отступ',
      },
      {
        title: 'id selector',
        description: 'Применяет стиль к элементу с конкретным id.',
        example: '#hero { min-height: 100vh; }',
        result: 'Элемент с id hero получит указанную высоту',
      },
    ],
  },
  {
    id: 'css-selectors-specificity',
    sectionId: 'css',
    order: 2,
    title: 'Селекторы и специфичность',
    description:
      'После основ важно разобраться, как выбирать элементы и как браузер решает конфликт правил.',
    path: '/css/lessons/css-selectors-specificity',
    rows: [
      {
        title: 'tag selector',
        description: 'Применяет стиль ко всем элементам указанного тега.',
        example: 'p { line-height: 1.6; }',
        result: 'Все абзацы получат line-height 1.6',
      },
      {
        title: '.class selector',
        description: 'Выбирает элементы по классу.',
        example: '.button { border-radius: 12px; }',
        result: 'Элементы с классом button получат скругление',
      },
      {
        title: '#id selector',
        description: 'Выбирает элемент по id.',
        example: '#app { min-height: 100vh; }',
        result: 'Элемент с id app получит минимальную высоту экрана',
      },
      {
        title: '[attribute]',
        description: 'Позволяет стилизовать элементы по атрибуту.',
        example: 'input[type="email"] { border-color: teal; }',
        result: 'Поля email получат другой цвет рамки',
      },
      {
        title: 'specificity',
        description: 'Определяет, какой селектор выиграет при конфликте стилей.',
        example: '#title { color: red; }\n.title { color: blue; }',
        result: 'Текст станет красным, потому что id специфичнее',
      },
      {
        title: '!important',
        description: 'Форсирует применение правила, но использовать нужно редко.',
        example: '.hidden { display: none !important; }',
        result: 'Правило перекроет большинство обычных стилей',
      },
    ],
  },
  {
    id: 'css-box-model',
    sectionId: 'css',
    order: 3,
    title: 'Блочная модель',
    description: 'После основ разбираем размеры, отступы и границы элементов.',
    path: '/css/lessons/css-box-model',
    rows: [
      {
        title: 'width / height',
        description: 'Задают размеры элемента.',
        example: 'width: 320px;\nheight: 120px;',
        result: 'Элемент получит указанные размеры',
      },
      {
        title: 'padding',
        description: 'Внутренний отступ между контентом и границей.',
        example: 'padding: 24px;',
        result: 'Контент отодвинется внутрь элемента',
      },
      {
        title: 'margin',
        description: 'Внешний отступ вокруг элемента.',
        example: 'margin-bottom: 16px;',
        result: 'Под элементом появится дополнительное пространство',
      },
      {
        title: 'border',
        description: 'Рисует границу элемента.',
        example: 'border: 1px solid #334155;',
        result: 'У элемента появится рамка',
      },
      {
        title: 'box-sizing',
        description: 'Определяет, как рассчитываются размеры элемента.',
        example: 'box-sizing: border-box;',
        result: 'Padding и border будут включены в width и height',
      },
    ],
  },
  {
    id: 'css-units-sizing',
    sectionId: 'css',
    order: 4,
    title: 'Единицы измерения и размеры',
    description:
      'Junior должен понимать абсолютные и относительные единицы, а также ограничения размеров.',
    path: '/css/lessons/css-units-sizing',
    rows: [
      {
        title: 'px',
        description: 'Фиксированная единица измерения для точных размеров.',
        example: 'width: 320px;',
        result: 'Ширина элемента станет 320 пикселей',
      },
      {
        title: '%',
        description: 'Задает размер относительно родительского элемента.',
        example: 'width: 50%;',
        result: 'Элемент займет половину ширины родителя',
      },
      {
        title: 'rem',
        description: 'Относительная единица от размера шрифта корневого html.',
        example: 'font-size: 1.25rem;',
        result: 'Размер текста будет зависеть от root font-size',
      },
      {
        title: 'em',
        description: 'Относительная единица от текущего размера шрифта элемента.',
        example: 'padding: 1em;',
        result: 'Отступ будет зависеть от font-size самого элемента',
      },
      {
        title: 'vw / vh',
        description: 'Единицы от размеров окна браузера.',
        example: 'min-height: 100vh;',
        result: 'Элемент займет высоту экрана',
      },
      {
        title: 'min-width / max-width',
        description: 'Ограничивают размеры элемента сверху и снизу.',
        example: 'width: 100%;\nmax-width: 1200px;',
        result: 'Блок растянется, но не станет шире 1200px',
      },
    ],
  },
  {
    id: 'css-typography',
    sectionId: 'css',
    order: 5,
    title: 'Типографика',
    description:
      'Отдельный обязательный блок: шрифты, размеры, интерлиньяж и базовая работа с текстом.',
    path: '/css/lessons/css-typography',
    rows: [
      {
        title: 'font-family',
        description: 'Задает семейство шрифтов для текста.',
        example: 'font-family: "Manrope", sans-serif;',
        result: 'Текст будет отображаться выбранным шрифтом',
      },
      {
        title: 'font-weight',
        description: 'Управляет толщиной шрифта.',
        example: 'font-weight: 700;',
        result: 'Текст станет жирнее',
      },
      {
        title: 'line-height',
        description: 'Задает высоту строки и влияет на читаемость текста.',
        example: 'line-height: 1.6;',
        result: 'Строки получат больше воздуха между собой',
      },
      {
        title: 'letter-spacing',
        description: 'Изменяет расстояние между буквами.',
        example: 'letter-spacing: 0.08em;',
        result: 'Буквы будут расположены чуть дальше друг от друга',
      },
      {
        title: 'text-transform',
        description: 'Меняет регистр текста без изменения исходной строки.',
        example: 'text-transform: uppercase;',
        result: 'Текст будет показан в верхнем регистре',
      },
      {
        title: 'text-align',
        description: 'Выравнивает текст внутри блока.',
        example: 'text-align: center;',
        result: 'Текст окажется по центру',
      },
    ],
  },
  {
    id: 'css-colors-backgrounds',
    sectionId: 'css',
    order: 6,
    title: 'Цвета, фоны и декоративные эффекты',
    description:
      'Базовый набор CSS для junior включает уверенную работу с цветами, градиентами, тенями и скруглениями.',
    path: '/css/lessons/css-colors-backgrounds',
    rows: [
      {
        title: 'color formats',
        description: 'Цвета можно задавать через hex, rgb, rgba, hsl.',
        example: 'color: rgba(255, 255, 255, 0.8);',
        result: 'Текст станет белым с прозрачностью 0.8',
      },
      {
        title: 'background-image',
        description: 'Позволяет использовать изображение или градиент как фон.',
        example: 'background-image: linear-gradient(135deg, #0f172a, #1d4ed8);',
        result: 'У элемента появится градиентный фон',
      },
      {
        title: 'background-size',
        description: 'Управляет масштабом фонового изображения.',
        example: 'background-size: cover;',
        result: 'Фон заполнит блок полностью',
      },
      {
        title: 'border-radius',
        description: 'Скругляет углы блока.',
        example: 'border-radius: 24px;',
        result: 'У элемента появятся скругленные углы',
      },
      {
        title: 'box-shadow',
        description: 'Добавляет внешнюю тень элементу.',
        example: 'box-shadow: 0 12px 30px rgba(0, 0, 0, 0.18);',
        result: 'Блок визуально приподнимется над фоном',
      },
      {
        title: 'opacity',
        description: 'Управляет прозрачностью элемента.',
        example: 'opacity: 0.6;',
        result: 'Элемент станет полупрозрачным',
      },
    ],
  },
  {
    id: 'css-layout',
    sectionId: 'css',
    order: 7,
    title: 'Поток документа и позиционирование',
    description: 'Дальше нужно понять display, position и управление потоком.',
    path: '/css/lessons/css-layout',
    rows: [
      {
        title: 'display',
        description: 'Определяет тип отображения элемента.',
        example: 'display: block;',
        result: 'Элемент займет всю доступную ширину строки',
      },
      {
        title: 'display: inline / inline-block',
        description: 'Позволяют элементу вести себя как строчный или смешанный блок.',
        example: '.tag { display: inline-block; }',
        result: 'Элемент останется в строке, но сможет иметь width и height',
      },
      {
        title: 'position: relative',
        description: 'Создает точку отсчета для абсолютно позиционированных потомков.',
        example: 'position: relative;',
        result: 'Дочерние absolute-элементы будут позиционироваться от него',
      },
      {
        title: 'position: absolute',
        description: 'Извлекает элемент из потока и позиционирует вручную.',
        example: 'position: absolute;\ntop: 0;\nright: 0;',
        result: 'Элемент окажется в правом верхнем углу контейнера',
      },
      {
        title: 'z-index',
        description: 'Управляет порядком наложения элементов.',
        example: 'z-index: 10;',
        result: 'Элемент окажется выше элементов с меньшим z-index',
      },
      {
        title: 'overflow',
        description: 'Определяет, что делать с контентом, выходящим за границы блока.',
        example: 'overflow: hidden;',
        result: 'Лишний контент будет скрыт',
      },
      {
        title: 'visibility / display none',
        description: 'Оба способа скрывают элемент, но по-разному влияют на поток.',
        example: '.hidden { display: none; }',
        result: 'Элемент исчезнет и перестанет занимать место в раскладке',
      },
    ],
  },
  {
    id: 'css-pseudo',
    sectionId: 'css',
    order: 8,
    title: 'Псевдоклассы и псевдоэлементы',
    description:
      'Для интерактивных интерфейсов junior должен знать состояния элементов и декоративные вставки.',
    path: '/css/lessons/css-pseudo',
    rows: [
      {
        title: ':hover',
        description: 'Стили при наведении курсора.',
        example: '.button:hover { transform: translateY(-2px); }',
        result: 'Кнопка изменит вид при наведении',
      },
      {
        title: ':focus',
        description: 'Стили для элемента в фокусе.',
        example: 'input:focus { outline: 2px solid #2563eb; }',
        result: 'Поле будет заметно выделено при фокусе',
      },
      {
        title: ':first-child',
        description: 'Выбирает первый дочерний элемент.',
        example: 'li:first-child { font-weight: 700; }',
        result: 'Первый элемент списка станет жирным',
      },
      {
        title: '::before',
        description: 'Добавляет декоративный псевдоэлемент перед контентом.',
        example: '.link::before { content: "→ "; }',
        result: 'Перед текстом ссылки появится стрелка',
      },
      {
        title: '::after',
        description: 'Добавляет декоративный псевдоэлемент после контента.',
        example: '.badge::after { content: " new"; }',
        result: 'После текста появится дополнительная подпись',
      },
      {
        title: 'content',
        description: 'Задает содержимое для before и after.',
        example: 'content: "";',
        result: 'Псевдоэлемент станет видимым и готовым к стилизации',
      },
    ],
  },
  {
    id: 'css-flexbox',
    sectionId: 'css',
    order: 9,
    title: 'Flexbox',
    description:
      'Полный базовый справочник по Flexbox: свойства контейнера и свойства flex-элементов.',
    path: '/css/lessons/css-flexbox',
    rows: [
      {
        title: 'display: flex',
        description: 'Включает flex-контекст для дочерних элементов.',
        example: 'display: flex;',
        result: 'Дочерние элементы выстроятся по одной оси',
      },
      {
        title: 'flex-direction',
        description: 'Определяет направление главной оси flex-контейнера.',
        example: 'flex-direction: column;',
        result: 'Элементы выстроятся сверху вниз',
      },
      {
        title: 'flex-wrap',
        description: 'Разрешает перенос элементов на новую строку.',
        example: 'flex-wrap: wrap;',
        result: 'Элементы будут переноситься при нехватке места',
      },
      {
        title: 'flex-flow',
        description: 'Краткая запись для flex-direction и flex-wrap.',
        example: 'flex-flow: row wrap;',
        result: 'Элементы выстроятся в строку и смогут переноситься',
      },
      {
        title: 'justify-content',
        description: 'Выравнивает элементы по главной оси.',
        example: 'justify-content: space-between;',
        result: 'Элементы распределятся с равными промежутками',
      },
      {
        title: 'align-items',
        description: 'Выравнивает элементы по поперечной оси.',
        example: 'align-items: center;',
        result: 'Элементы будут выровнены по центру по высоте',
      },
      {
        title: 'align-content',
        description: 'Управляет выравниванием нескольких строк flex-элементов.',
        example: 'align-content: space-between;',
        result: 'Несколько строк будут распределены по высоте контейнера',
      },
      {
        title: 'gap',
        description: 'Задает расстояние между flex-элементами.',
        example: 'gap: 16px;',
        result: 'Между элементами появится отступ 16px',
      },
      {
        title: 'row-gap / column-gap',
        description: 'Позволяют отдельно задать вертикальные и горизонтальные промежутки.',
        example: 'row-gap: 12px;\ncolumn-gap: 24px;',
        result: 'Вертикальные и горизонтальные отступы будут различаться',
      },
      {
        title: 'order',
        description: 'Меняет визуальный порядок отдельного flex-элемента.',
        example: '.item--first { order: -1; }',
        result: 'Элемент визуально переместится раньше остальных',
      },
      {
        title: 'flex-grow',
        description: 'Определяет, как элемент растягивается, занимая свободное место.',
        example: '.item { flex-grow: 1; }',
        result: 'Элемент начнет расширяться внутри контейнера',
      },
      {
        title: 'flex-shrink',
        description: 'Определяет, может ли элемент сжиматься при нехватке места.',
        example: '.item { flex-shrink: 0; }',
        result: 'Элемент не будет ужиматься меньше базового размера',
      },
      {
        title: 'flex-basis',
        description: 'Задает базовый размер flex-элемента до распределения свободного места.',
        example: '.item { flex-basis: 240px; }',
        result: 'Начальный размер элемента составит 240px',
      },
      {
        title: 'flex',
        description: 'Краткая запись для flex-grow, flex-shrink и flex-basis.',
        example: '.item { flex: 1 1 240px; }',
        result: 'Элемент сможет расти, сжиматься и стартовать с 240px',
      },
      {
        title: 'align-self',
        description: 'Позволяет переопределить выравнивание конкретного flex-элемента.',
        example: '.item { align-self: flex-end; }',
        result: 'Один элемент выровняется по нижнему краю поперечной оси',
      },
    ],
  },
  {
    id: 'css-grid',
    sectionId: 'css',
    order: 10,
    title: 'CSS Grid',
    description:
      'Полный базовый справочник по Grid: сетка контейнера, размещение элементов и именованные области.',
    path: '/css/lessons/css-grid',
    rows: [
      {
        title: 'display: grid',
        description: 'Включает Grid-контекст для дочерних элементов.',
        example: 'display: grid;',
        result: 'Контейнер начнет работать как grid',
      },
      {
        title: 'grid-template-columns',
        description: 'Задает структуру колонок сетки.',
        example: 'grid-template-columns: 240px 1fr 1fr;',
        result: 'Сетка будет состоять из трех колонок',
      },
      {
        title: 'grid-template-rows',
        description: 'Задает структуру строк сетки.',
        example: 'grid-template-rows: auto 1fr auto;',
        result: 'Сетка получит три строки с разными размерами',
      },
      {
        title: 'repeat()',
        description: 'Сокращает запись повторяющихся колонок или строк.',
        example: 'grid-template-columns: repeat(4, 1fr);',
        result: 'Будут созданы 4 равные колонки',
      },
      {
        title: 'minmax()',
        description: 'Позволяет задать диапазон размеров трека.',
        example: 'grid-template-columns: repeat(3, minmax(180px, 1fr));',
        result: 'Колонки не будут уже 180px, но смогут растягиваться',
      },
      {
        title: 'gap',
        description: 'Задает расстояние между строками и колонками сетки.',
        example: 'gap: 20px;',
        result: 'Между ячейками появится отступ 20px',
      },
      {
        title: 'justify-items',
        description: 'Выравнивает содержимое ячеек по горизонтали.',
        example: 'justify-items: center;',
        result: 'Элементы внутри ячеек будут выровнены по центру',
      },
      {
        title: 'align-items',
        description: 'Выравнивает содержимое ячеек по вертикали.',
        example: 'align-items: start;',
        result: 'Элементы внутри ячеек прижмутся к верхнему краю',
      },
      {
        title: 'justify-content',
        description: 'Выравнивает всю grid-сетку по горизонтали внутри контейнера.',
        example: 'justify-content: center;',
        result: 'Вся сетка будет центрирована внутри контейнера',
      },
      {
        title: 'align-content',
        description: 'Выравнивает всю grid-сетку по вертикали внутри контейнера.',
        example: 'align-content: space-between;',
        result: 'Строки сетки распределятся по высоте контейнера',
      },
      {
        title: 'grid-column',
        description: 'Определяет, между какими вертикальными линиями расположен элемент.',
        example: '.card { grid-column: 1 / 3; }',
        result: 'Элемент займет две колонки',
      },
      {
        title: 'grid-row',
        description: 'Определяет, между какими горизонтальными линиями расположен элемент.',
        example: '.card { grid-row: 1 / 3; }',
        result: 'Элемент займет две строки',
      },
      {
        title: 'grid-area',
        description: 'Краткая запись для grid-row-start, grid-column-start и связанных свойств.',
        example: '.hero { grid-area: 1 / 1 / 3 / 3; }',
        result: 'Элемент займет прямоугольную область 2x2',
      },
      {
        title: 'grid-template-areas',
        description: 'Позволяет описать сетку именованными областями.',
        example:
          'grid-template-areas: "header header" "sidebar content" "footer footer";',
        result: 'Области сетки можно будет назначать по именам',
      },
      {
        title: 'place-items / place-content',
        description: 'Краткая запись для align/justify-items и align/justify-content.',
        example: 'place-items: center;\nplace-content: center;',
        result: 'Содержимое ячеек и вся сетка будут центрированы',
      },
    ],
  },
  {
    id: 'css-forms-tables',
    sectionId: 'css',
    order: 11,
    title: 'Стилизация форм и таблиц',
    description:
      'Практический junior-набор: аккуратно оформлять инпуты, кнопки, таблицы и их состояния.',
    path: '/css/lessons/css-forms-tables',
    rows: [
      {
        title: 'appearance: none',
        description: 'Сбрасывает нативный вид некоторых элементов формы.',
        example: 'select { appearance: none; }',
        result: 'Элемент можно стилизовать более свободно',
      },
      {
        title: 'outline',
        description: 'Отвечает за обводку, часто используется для focus-состояний.',
        example: 'input:focus { outline: 2px solid #3b82f6; }',
        result: 'Фокус станет заметным пользователю',
      },
      {
        title: 'cursor',
        description: 'Меняет вид курсора над элементом.',
        example: 'button { cursor: pointer; }',
        result: 'Курсор покажет, что элемент кликабельный',
      },
      {
        title: 'border-collapse',
        description: 'Управляет тем, как схлопываются границы таблицы.',
        example: 'table { border-collapse: collapse; }',
        result: 'Границы ячеек объединятся без двойных линий',
      },
      {
        title: ':disabled',
        description: 'Стилизует неактивные поля и кнопки.',
        example: 'button:disabled { opacity: 0.5; }',
        result: 'Неактивная кнопка станет визуально приглушенной',
      },
      {
        title: 'resize',
        description: 'Управляет возможностью изменять размер textarea.',
        example: 'textarea { resize: vertical; }',
        result: 'Пользователь сможет менять высоту поля, но не ширину',
      },
    ],
  },
  {
    id: 'css-responsive-animation',
    sectionId: 'css',
    order: 12,
    title: 'Адаптивность и анимации',
    description: 'Завершаем CSS медиа-правилами, трансформациями и анимацией.',
    path: '/css/lessons/css-responsive-animation',
    rows: [
      {
        title: '@media',
        description: 'Применяет стили только при выполнении условия.',
        example: '@media (max-width: 768px) { .grid { grid-template-columns: 1fr; } }',
        result: 'На узких экранах сетка перестроится в одну колонку',
      },
      {
        title: 'mobile-first',
        description: 'Подход, при котором сначала пишутся стили для мобильной версии.',
        example:
          '.card { padding: 16px; }\n@media (min-width: 768px) { .card { padding: 24px; } }',
        result: 'Базовые стили будут работать на маленьких экранах по умолчанию',
      },
      {
        title: 'transition',
        description: 'Анимирует изменение CSS-свойств.',
        example: 'transition: transform 0.2s ease;',
        result: 'Изменение transform станет плавным',
      },
      {
        title: 'transform',
        description: 'Позволяет сдвигать, масштабировать и вращать элементы.',
        example: 'transform: translateY(-4px);',
        result: 'Элемент поднимется вверх на 4px',
      },
      {
        title: '@keyframes',
        description: 'Описывает шаги CSS-анимации.',
        example: '@keyframes fadeIn { from { opacity: 0; } to { opacity: 1; } }',
        result: 'Появится анимация плавного появления',
      },
      {
        title: 'animation',
        description: 'Запускает анимацию, созданную через keyframes.',
        example: 'animation: fadeIn 0.6s ease;',
        result: 'Элемент проиграет анимацию fadeIn',
      },
      {
        title: 'object-fit',
        description: 'Управляет тем, как изображение или видео вписывается в блок.',
        example: 'img { width: 100%; height: 240px; object-fit: cover; }',
        result: 'Изображение заполнит блок без искажений пропорций',
      },
    ],
  },
  {
    id: 'react-intro',
    sectionId: 'react',
    order: 1,
    title: 'React и JSX',
    description: 'Начинаем с компонентов, JSX и базовой структуры React-приложения.',
    path: '/react/lessons/react-intro',
    rows: [
      {
        title: 'Компонент',
        description: 'Функция, которая возвращает React-разметку.',
        example: 'const App = () => <h1>Hello</h1>;',
        result: 'Компонент App отрисует заголовок',
      },
      {
        title: 'JSX',
        description: 'Синтаксис, похожий на HTML, внутри JavaScript.',
        example: 'const element = <button>Click</button>;',
        result: 'React создаст описание интерфейса',
      },
      {
        title: 'props',
        description: 'Позволяют передавать данные в компонент.',
        example: 'const Title = ({ text }) => <h1>{text}</h1>;',
        result: 'Title text="React" покажет React',
      },
      {
        title: 'children',
        description: 'Специальный prop для вложенного содержимого.',
        example: 'const Card = ({ children }) => <div>{children}</div>;',
        result: 'Внутрь Card можно передавать любой JSX',
      },
      {
        title: 'Fragment',
        description: 'Позволяет вернуть несколько элементов без лишнего div.',
        example: '<><h1>One</h1><p>Two</p></>',
        result: 'Элементы будут сгруппированы без дополнительного узла',
      },
    ],
  },
  {
    id: 'react-state-events',
    sectionId: 'react',
    order: 2,
    title: 'State и события',
    description: 'Следом изучаем локальное состояние и обработку действий пользователя.',
    path: '/react/lessons/react-state-events',
    rows: [
      {
        title: 'useState()',
        description: 'Добавляет локальное состояние в функциональный компонент.',
        example: 'const [count, setCount] = useState(0);',
        result: 'Компонент сможет хранить значение count',
      },
      {
        title: 'setState',
        description: 'Обновляет состояние и вызывает повторный рендер.',
        example: 'setCount((prev) => prev + 1);',
        result: 'count увеличится на 1',
      },
      {
        title: 'onClick',
        description: 'Обработчик клика по элементу.',
        example: '<button onClick={handleClick}>+</button>',
        result: 'При клике выполнится handleClick',
      },
      {
        title: 'controlled input',
        description: 'Поле ввода, значение которого хранится в state.',
        example: '<input value={name} onChange={(e) => setName(e.target.value)} />',
        result: 'Значение input полностью контролируется React',
      },
      {
        title: 'условный рендеринг',
        description: 'Позволяет показывать JSX в зависимости от условия.',
        example: '{isOpen && <Modal />}',
        result: 'Modal появится только если isOpen === true',
      },
    ],
  },
  {
    id: 'react-lists-effects',
    sectionId: 'react',
    order: 3,
    title: 'Списки и эффекты',
    description: 'После state логично перейти к рендерингу коллекций и побочным эффектам.',
    path: '/react/lessons/react-lists-effects',
    rows: [
      {
        title: 'array.map() в JSX',
        description: 'Используется для рендера списков компонентов.',
        example: '{items.map((item) => <li key={item.id}>{item.name}</li>)}',
        result: 'Каждый элемент массива будет отрисован как отдельный li',
      },
      {
        title: 'key',
        description: 'Уникальный ключ помогает React отслеживать элементы списка.',
        example: '<li key={item.id}>{item.name}</li>',
        result: 'React корректно обновит список при изменениях',
      },
      {
        title: 'useEffect()',
        description: 'Запускает побочный эффект после рендера компонента.',
        example: 'useEffect(() => {\n  document.title = "React";\n}, []);',
        result: 'Заголовок документа обновится после монтирования',
      },
      {
        title: 'dependency array',
        description: 'Определяет, когда effect должен перезапускаться.',
        example: 'useEffect(() => {\n  loadUser(userId);\n}, [userId]);',
        result: 'Эффект выполнится при изменении userId',
      },
      {
        title: 'cleanup',
        description: 'Функция очистки выполняется перед размонтированием или повторным запуском.',
        example: 'useEffect(() => {\n  const id = setInterval(tick, 1000);\n  return () => clearInterval(id);\n}, []);',
        result: 'Интервал будет корректно очищен',
      },
    ],
  },
  {
    id: 'react-forms-lifting',
    sectionId: 'react',
    order: 4,
    title: 'Формы и подъем состояния',
    description: 'Важный блок про управление данными между несколькими компонентами.',
    path: '/react/lessons/react-forms-lifting',
    rows: [
      {
        title: 'onChange',
        description: 'Позволяет реагировать на изменение поля.',
        example: '<input onChange={(event) => setValue(event.target.value)} />',
        result: 'State будет обновляться при вводе',
      },
      {
        title: 'submit handler',
        description: 'Обрабатывает отправку формы в React.',
        example: '<form onSubmit={handleSubmit}></form>',
        result: 'Функция handleSubmit вызовется при отправке',
      },
      {
        title: 'preventDefault()',
        description: 'Не дает браузеру перезагружать страницу при submit.',
        example: 'const handleSubmit = (event) => event.preventDefault();',
        result: 'Отправка формы будет обработана в React',
      },
      {
        title: 'lifting state up',
        description: 'Общее состояние выносится в ближайший общий родитель.',
        example: '<Parent><Input /><Preview /></Parent>',
        result: 'Несколько компонентов смогут работать с одними данными',
      },
      {
        title: 'props drilling',
        description: 'Передача данных через несколько уровней компонентов.',
        example: '<Page user={user} />',
        result: 'Нижележащие компоненты получат доступ к user через props',
      },
    ],
  },
  {
    id: 'react-routing-state',
    sectionId: 'react',
    order: 5,
    title: 'Маршрутизация и состояние приложения',
    description: 'Завершаем стартовый React-блок навигацией и общим состоянием.',
    path: '/react/lessons/react-routing-state',
    rows: [
      {
        title: '<BrowserRouter>',
        description: 'Подключает маршрутизацию в React-приложении.',
        example: '<BrowserRouter><App /></BrowserRouter>',
        result: 'Приложение начнет поддерживать маршруты',
      },
      {
        title: '<Routes> и <Route>',
        description: 'Описывают набор маршрутов приложения.',
        example: '<Routes><Route path="/" element={<Home />} /></Routes>',
        result: 'По адресу / отрисуется компонент Home',
      },
      {
        title: 'useNavigate()',
        description: 'Позволяет менять маршрут программно.',
        example: 'const navigate = useNavigate();\nnavigate("/profile");',
        result: 'Пользователь будет перенаправлен на /profile',
      },
      {
        title: 'Redux store',
        description: 'Централизованное хранилище состояния приложения.',
        example: 'const store = configureStore({ reducer });',
        result: 'Общее состояние станет доступно через Provider',
      },
      {
        title: 'useSelector / useDispatch',
        description: 'Хуки для чтения состояния и отправки action в Redux.',
        example: 'const count = useSelector(selectCount);',
        result: 'Компонент получит данные из store',
      },
    ],
  },
];
